### ISSUE TITLE
[C] 홈 / 검색 기능

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#10]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail: 

# TODO
 - [x] 크기, 공간, 종류 조건을 받아 서버에 검색 요청
 - [x] 서버에서 성공 응답 오면 검색 결과 페이지로 이동
 - [x] 검색 결과 페이지에서 서버의 응답으로 온 데이터 보여주기
 - [x] 서버코드랑 연결 확인
