### ISSUE TITLE
SR 기획

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#11]
# ISSUE
* Group:`sr`
# TODO
-  [x] Team Introduction *
-  [x] Team Rule * 
- [x] Requirements *
- [x] Stack * 
- [x]  태스크 카드 작성
- [x] 아키텍처 다이어그램
- [x] API : 사진 업로드, 삭제 API 작성
- [x] SR  빠진 항목 없는지 확인 **(팀 명: Gardener/인증 실패메세지 : 추후 고려/혹여나 SR 설문때 미리 공유할 내용 있으면 생각해 보기 !)
- [x] 깃 초기 세팅 (npm init -y , )
- [x] 필요한 모듈 정리
- [x] 프론트 백엔드 각자 나누어져서 초반부에 해야 할 작업들(태스크 분배/디렉토리 구조 작성/모듈 설치 등) 4-50분 정도 진행 후 모여서 어디까지 작업했는지 공유
