### ISSUE TITLE
[C] 식물 상세페이지

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#12]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail: 사용자가 클릭한 식물의 상세 정보가 나오는 창입니다

# TODO
 - [x] 선택된 식물 아이디를 서버에 보내기
 - [x] 서버에서 선택된 식물 이름, 식물 사진, 식물 설명, 인테리어 사진 배열 받아오기
-  [x] 잘 띄워주기
- [x] 서버코드랑 연결 확인
