### ISSUE TITLE
[C] 마이페이지 / 회원정보 조회

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#13]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail:  회원 정보(email) 조회

# TODO
 - [x] 마이페이지 버튼이 눌리면, 서버에 GET요청 보내기
 - [x] 응답으로 받은 유저 정보(email) 띄우기
 - [x] 서버코드랑 연결 확인
