### ISSUE TITLE
5.3 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#138]
# ISSUE
* Group: 
* Type:
* Detail: 

# TODO
 - [x] KPT 회고 공유: 특이사항 또는 도움이 필요한 사항 체크 후 제출
 - [x] 스몰톡 안건 미리 정리: 5/6(금) 11:00-11:45에 일정 있음
 - 스목톡 안건 적는 링크:  https://github.com/codestates/Pida/issues/144
 - [x] 기능구현 중 특이사항이나 일정 관련 힘든점 or 에러 공유
 - 프론트: 댓글 수정 부분
 - 백엔드: 게시글 수정 기능구현 완료, 이미지 파일 크기는 최대 3MB로 해도 될거같아요
 - [x] 당일 오전: 베어미니멈 테스트케이스 정리 및 정상 작동 확인: 에러 사항 리스트업
 - [x] 오후: 버그 수정, 특이사항 있을 시 구글밋 or 디코
 - [x] 만일 버그 수정 오늘 5시 전으로 마무리 될 시, adv 부분 태스크 카드 만들어놓고 구현 시작하자. 
 - [x] 5시 특이사항 공유 & 오늘 저녁 or 내일 할 작업 선정 
 - [ ] 위키에 배포링크 걸어두기?!
