### ISSUE TITLE
[S] 베어미니멈 버그 수정

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#139]
# ISSUE
* Group: `server`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] 형석님 추가하신 식물정보 DB 반영
 - [x] 게시글 CRUD 관련 api 반영
 - [x] api 재검토, 용어 통일. 
 - [x] 서버 테스트 케이스 리스트업
 - [x] 버그 수정, 정상 작동 확인
