### ISSUE TITLE
[S] 식물 전체보기 & 상세페이지 기능 강화

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#140]
# ISSUE
* Group: `server`
* Type:  `feature`
* Detail: 

# TODO
 - [x] 식물 전체데이터 보기: api
 - [x] 식물 상세페이지 하단의 사진들: 인기순 정렬 기능 구현 api
 - [x] 식물 상세페이지 하단의 사진들: 최신순 정렬 기능 구현 api
 - [x] 좋아요 개수 표시 기능
 - [x] 채팅기능 자료조사
