### ISSUE TITLE
[S] 식물 상세페이지

### ISSUE THREAD

**Issue by yuriiiiiiiiiii** [codestates/Pida#15]
# ISSUE
* Group: `server`
* Type:  `feature`
* Detail: 식물 상세페이지 렌더링을 위해 필요한 정보 쿼리문으로 가지고 와서, 컨트롤러에서 클라이언트 측으로 보내주기 

# TODO
 - [x] plant 테이블 상세 정보 불러오기 쿼리문 작성
 - [x] interior 사진 정보 불러오기 쿼리문 작성
-  [x] 상위 두 정보 통합하여 클라이언트로 보내주는 컨트롤러 작성
