### ISSUE TITLE
5.4 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#159]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [ ] 금요일 9시 전까지 KPT 회고작성: 카드만들었어요
 - [ ] 당일 작업 & 특이사항 공유
 -  백엔드:
   - 좋아요 개수 표시 기능 구현 완료. 추후 에러 점검 후 채팅기능 구현: https 프로토콜에 적용하는 법 , 
   -  채팅 : 테스트용으로 미니서버 만들어서 적용해보기
   -  유효성 검사 모듈 적용 시 새니타이저 사용 (로그인 회원가입 닉넴수정 비번수정 글쓰기 텍스트) 마무리. - 오늘 채팅 이후 남는시간에 

* 최신순 인기순 정렬 이상: 계속 같은 글만 보임-> 서버측 데이터 이상
* 좋아요 숫
---------------------------------------------
**5월 4일 저녁 8시 회의 결론**
 처음부터 1:1 채팅 구현하기: 리덕스 적용에서 어려움이 있을 것으로 예상함, 시간적으로 소모가 많을 것 같음
그래서 다른 기능들 먼저 구현을 하는 걸로 결정.
**[이번주]**
- [ ] 소셜로그인: 
  -  **총 2개 붙이기**
  - 깃허브 먼저 붙여보고, 잘 되면 나머지 매체 중 하나 더 선정해서 붙여보자(레퍼런스 많은 쪽or 네이버, 구글, 카카오 중 하나 고려)
- [ ] 반응형: 시간 조금 필요
---------------------------------------------------------------
**[다음주]**
페이지네이션
비번 찾기 -> 이멜인증
식물정보 추가하는 관리자 페이지..? => 특정 번호를 관리자한테 줘서 토큰화 시킬 수 있음

**<채팅관련>**
우선 위의 기능 구현하고 잘 되서 시간 남을 시 시도.
프로젝트 이후에도 붙일 수 있다는 점 고려
네비바에 달아서 큰 채팅방,, 오픈채팅방처럼?
