### ISSUE TITLE
[S] 마이페이지 / 회원정보 조회

### ISSUE THREAD

**Issue by yuriiiiiiiiiii** [codestates/Pida#16]
# ISSUE
* Group: `server`
* Type: `feature`
* Detail: 마이페이지 / 회원 정보 조회

# TODO
 - [x] 마이페이지/회원정보 접속 시 해당 유저 email 정보 반환하는 쿼리
 - [x] 상기 컨트롤러 작성
 - [x] 더미 데이터 넣고 테스트 진행: 토큰 필요
