### ISSUE TITLE
[S] 소셜로그인 기능 구현- 깃허브

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#163]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] 사용자 테이블 컬럼 고려 및 추가
 - [x] 깃허브 로직 스터디
 - [x] 관련 코드 작성
