### ISSUE TITLE
[S] 식물 DB 관리자 페이지를 위한 CRUD 컨트롤러 작성

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#183]
# ISSUE
* Group:  `server`
* Type: `feature`
* Detail: 

# TODO
 - [x] CRUD 컨트롤러 작성
 - [x] 로컬 테스트 진행, S3 세팅 점검
 - [x] 버그 수정
 - [x] 월요일 머지 진행(이거 먼저 하고 검색로직 머지.)
 - [x] DB 테이블 채우고 CSV 파일 공유하기 ??
 - [ ] AWS 계정간 EC2 인스턴스 공유하기 - https://ibks-platform.tistory.com/m/36
