### ISSUE TITLE
[S] 식물 카테고리 테이블 변경으로 인한 검색 데이터 찾아주기 로직 수정 

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#185]
# ISSUE
* Group: `server`
* Type:  `feature`
* Detail: 

# TODO
 - [x] 식물 카테고리 테이블 변경으로 인한 검색 데이터 찾아주기 로직 수정 
 - [x] 로컬 테스트 진행 (로그인 유무 확인)
 - [x]  월요일 머지 진행
