### ISSUE TITLE
[C] 마이페이지 / 회원탈퇴

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#19]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail: 회원 탈퇴 기능 구현

# TODO
 - [x] 회원탈퇴 버튼이 눌리면, 정말 탈퇴할 것인지 확인 모달
 - [x] 취소 버튼이 눌리면, 돌아가기
 - [x] 확인 버튼이 눌리면, 서버에 탈퇴 요청
 - [x] 서버에서 성공 응답 오면 메인 페이지로 이동해 성공 모달
 - [x] 서버코드랑 연결 확인
