### ISSUE TITLE
5.9 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#191]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [ ] 내일 오전 9시 전까지 KPT 작성 https://github.com/codestates/Pida/issues/196#issue-1229013764
 - [x] 관리자 계정 : 디코에 공지해뒀습니다.
 - [ ] 브랜치 머지 및 코드 작업 특이사항 공유
   - 반응형 웹
   - 관리자 ID는 env 파일에 저장해뒀습니다.
   - 식물 DB 관리자 CRUD 버그
   - **식물 등록, 수정 시 체크박스 부분: 방법 간단히 설명, 공유**
     - **구현 완료**
     - 클라이언트에서 보낼때 순서 맞춰서 보내도록 구현해두었어요
     - 배열에 숫자추가시 e.target.value => parseInt(e.target.value)로 수정
     - 체크박스 이벤트명 onClick => onChange로 수정
     - 수정 시 , 기존 데이터 값을 체크박스에 반영하는 방법: plantModify 파일에 적용완료.
   - **카카오 로그인 서버 코드 머지**(클라이언트 아이디 공유필요함, 카카오맵 애플리케이션 공동관리 위해 팀원초대)
   - 카카오 클라이언트 측 코드는 서버 쪽에서도 작성해본게 있어요.(로컬에서 이상없었음)
   - 현재 깃허브 ,카카오 2가지 있기 때문에, **콜백파일은 githubcallbak, kakaocallback 이렇게 따로 만들어야 해요.**
   - 리디렉션 url은 https://pida.ga/githubcallback , https://pida.ga/kakaocallback 이렇게 설정해두겠습니다.
   - **회원가입시 이메일 인증기능 필요**함. (유효하지 않은 이메일, 다른  사람 이메일 탈취하여 가입하는 것 방지 위해 )논의필요
  
 - 오늘 작업: 
   - [ ] 반응형 웹페이지 작업
   - [x] 관리자페이지 버그수정
   - [x] 카카오로그인 버그수정 및 소셜로그인 파일 정리
   - [ ] 카카오맵 API 활용하여 마이페이지에 주변 꽃집 찾아주기 기능 추가하기(2.5-3일 예상):
     -  API 문서 읽고 쓸 수 있을만한 API 찾아 정리하고 적용 시도해보기
     - [레퍼런스](https://wannabeph.medium.com/%EC%B9%B4%EC%B9%B4%EC%98%A4-%EB%A7%B5-api%ED%99%9C%EC%9A%A9%ED%95%B4%EC%84%9C-%EB%82%B4-%EC%9C%84%EC%B9%98-%EC%A3%BC%EB%B3%80-%EC%B6%A9%EC%A0%84%EC%86%8C%EB%93%A4%EC%9D%98-%EC%9C%84%EC%B9%98%EB%A5%BC-%EB%B3%B4%EC%97%AC%EC%A3%BC%EA%B3%A0-%EA%B8%B8%EC%B0%BE%EA%B8%B0-%EA%B8%B0%EB%8A%A5-%EC%A0%81%EC%9A%A9-2-3-3daecdda57f)
 - 금주 작업: 카카오 지도API 작업 이후로는 이메일 인증기능, 비번 분실기능 등 , (무한스크롤) 적용
 
 - 5시 회의 안건
   - 지도 API 중 쓸 수 있을 만한 것 선별하여 공유하기, (적용해본 게 있다면 그것도 공유), 저녁 ~

- 다음날
  - 지도 api 관련 작업내용 공유
  -
