### ISSUE TITLE
[C] 인테리어 글 /  좋아요

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#20]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail:  마음에 드는 인테이어 글에 좋아요 누르기 기능

# TODO
 - [x] isLike가 false라면 인테리어 글 아이디와 함께 서버에 좋아요 요청
 - [x] 서버에서 성공 응답 오면 하트가 채워진 페이지 보여주기
 - [x] 서버코드랑 연결 확인
