### ISSUE TITLE
5.10 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#208]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] 카카오맵 API 적용: 페이지네이션까지 구현완료했고, 리스트에 마우스 올렸을 때 말풍선 뜨는것도 구현해야 할것 같습니다
 - [x] https://apis.map.kakao.com/web/sample/keywordList/
 - 당일 작업: 
   - [x] 카카오맵 버그 수정 
   - [x] 카카오맵 페이지 관련작업
   - [ ] 그리드
   - [x]  이메일 인증기능 조사 및 필요한 화면 정리해서 5시 회의할때 클라이언트분들에게 전달, 구현시도
 
- 5시 회의
   - [ ]  진행상황 점검
   - [ ] 리팩토링과 버그 수정은 주말 언제쯤?!
