### ISSUE TITLE
[C] [S] 프로젝트 정리

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#215]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [ ] 콘솔로그 제거
 - [ ] 페이지에 더미 게시글 쓰기!!
 - [ ] worklog 정리
 - [ ] 시스템 아키텍처 다시그리기
 - [ ] API 문서 정리
 - [ ] 환경변수 client ID, secret 재발급
 - [ ] 파일구조, 리팩토링 조금씩
 - [ ] 브랜치 머지
 - [ ] 발표자료준비
