### ISSUE TITLE
[S] 리팩토링, 검색 API 정리

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#216]
# ISSUE
* Group:  `server`
* Type:  `feature`
* Detail: 

# TODO
 - [x] 파일구조 리팩토링
 - [x] 데이터 내려받아 주는 부분 중 Promise.all 필요한 부분 있으면 개선
 - [x] 반복적으로 사용되는 함수는 별도의 미들웨어로 만들거나 모듈화
 - [x] 검색 API search/all  -> search로 통합, 클라이언트와 논의
