### ISSUE TITLE
5.11 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#223]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
   - [x] 백엔드 이메일 인증기능 구현, 오전 중 재검토 후 머지예정
   - [x] search api 리팩토링했습니다, 클라이언트 쪽에서는 전체 검색 시 /search/all 말고 /search로 요청 부탁드립니다.
   - [x] 프론트 그리드 작업, 이메일 인증기능
   - [x] 이메일 인증 관련하여 버그나 특이사항 있을 경우 논의할것
   - [x]  환경변수 중 client ID, secret 재발급하여 공유(깃허브, 카카오, 카카오맵)
   - [ ] **위 모든 작업 마무리 이후, 다른 버그 없는지 재검토** (버그 확인 후 디코에 모아뒀다가 한번에 처리)=>` 목요일 중으로 끝내기!!`

### 5시 회의
- [x] 서버 리팩터하고 머지 후 이상 생겼던 부분?
- [x] 푸터를 모든 페이지에 적용!!
- [x] 비회원이 글쓰기 누를 시 로그인 창 유도
- [x] 비동기 처리- 데이터 받아오기 정리
- [x] 저녁 이력서 특강 8:00 -9:30
- [x] 금주 스몰톡에 드릴 질문이나 안건 있으면 아래 댓글로 남겨주세요!
- [x] 서버 express validator 유효성 검사 로직 적용도 필요한데, 일단 이건 별도의 파일로 만들어서 해보고 잘 될때만 머지하겠다. (발표 이후로 생각해볼것) 
---
위 작업 이후 할것
   - [x] 검색 기능 이외 나머지 부분 백엔드/프론트 리팩토링: (gif 만든 이후에 할것)조금씩 나눠서 커밋, 기능 정상적인지 확인    
   - [x] 발표준비하기(일-월): .env.example 파일 정리, 식물오탈자 수정, 위키페이지 수정, 대본, gif 준비, 질의응답?? 준비(일요일 - 월요일 사이에 준비, 로고작업도 같이!!)

---
### 부가기능
별도의 파일에다가 작성한 후, 기능이 정상적일 경우 추후 덧붙이는 것으로.
 - [ ] 비번분실,,??
 - [ ] 무한스크롤
