### ISSUE TITLE
[C] 인테리어 글 / 삭제

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#24]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail: 인테리어 상세 페이지에서 삭제 버튼을 눌러 유저 본인이 업로드 한 글 삭제 가능

# TODO
 - [x] 인테리어 상세 모달에서 삭제 버튼 클릭 시, 취소 확인 모달이 뜨고, 확인 클릭 시 글 삭제
 - [x] 서버에서 성공 응답 오면 모달 닫고
 - [x] 해당 글이 삭제된 상태의 페이지 보여주기
 - [x] 서버코드랑 연결 확인
