### ISSUE TITLE
5.12 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#241]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 
<공통>
 - [ ] 토요일 오후5시-10시쯤에는 API 못볼수도있어요 스웨거 서버 다운타임때문에,,
 - [x] KPT 작성 https://github.com/codestates/Pida/issues/242#issue-1233280922
 - [x] 스몰톡 안건 정리: 아래 댓글로!!
 - [x] 검색 기능 버그 수정
 - [ ] 마무리 작업 태스크카드 :https://github.com/codestates/Pida/issues/215#issue-1230880156

<서버>
 - [x] 리팩토링 마지막으로 검토 후 오전 중 머지예정
 - [x] 추후 버그수정
 - [x] 회원가입시 카카오 닉네임에서 이모티콘 제거예정
 - [x] 카카오계정 로그아웃 시 쿠키가 삭제안됨 -> 서버측에서 로그아웃 처리예정(오늘중으로!)
 - [x] 별개의 파일 만들어서 validator 모듈 적용해보기 / AMI 공유(EC2 로그 공유) / 추후: 배포자동화 / 비번수정...

<클라이언트>
 - [x] 푸터 마무리 (주소받기): 메일주소, 블로그주소
 - [x] 버그수정
 - [ ] 페이지 스타일
 - [ ] 무한스크롤 검색,,

# 5시 회의
 
<공통>
 - [x] 버그 내역 공유 https://github.com/codestates/Pida/issues/238#issue-1232831410 , https://github.com/codestates/Pida/issues/249#issue-1233382931
 - [x] 이메일 인증 관련해 유저 테이블에 emailVerified 컬럼 추가했고, 로컬에서 테스트 시 이상 없었어요. (다들 괜찮다하면 머지할게요!)
 - [x] 클라이언트 서버 axios 버전 달라요 0.22.0통일
 - [ ] 추가적으로 할 작업 공유: API 검사/ 검색기능, 스크롤/비회원 권한 제한(글쓰기,댓글,좋아요)
 - [ ] 만약에 5시 전후로  다 끝날 시에는,,
 - [ ] 내일 스몰톡 하기전에 9시 모여서 팀 진도, 상황 간단히 정리하기
 - [ ] **내일 5시 줌에서 프로젝트 리플렉션 있다고 합니다!!!!!!!!!!!!!!!**
 - [ ] KPT
