### ISSUE TITLE
[C] 마이페이지 / 업로드 인테리어, 좋아요 인테리어 모아보기

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#25]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail:  유저는 자신이 업로드한 인테리어 글과, 좋아요 한 인테리어 글을 모아서 볼 수 있음

# TODO
 - [x] 마이페이지에서 '나의 인테리어' 버튼과 '관심 인테리어' 버튼을 클릭하면 각각 다른 컴포넌트를 불러 보여준다
 - [x] 컴포넌트에서 각 사진을 누르면 인테리어 상세 모달을 띄워준다 (인테리어 상세모달에서  useEffect로 get 요청을 보내기 때문에 여기서 따로 보낼 요청은 없다)
 - [x] 서버코드랑 연결 확인
