### ISSUE TITLE
5.13 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#263]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] KPT 회고 제출
 - [x] 스몰톡: 진도, 상황 정리, 질문 (현재 디자인 수정 보완 거의 다 됨, 테스트하며 부족한 로직 기능 보완 거의 완료, 위키페이지, 콘솔 등 정리 예정)
 - [x] 최종 버그 수정 -----늦어도 오늘 오후 4-5시 전까진 끝내기,, 그 이후부턴 아래 내용 수행
 - [x] console.log 정리
 ---
 - [x] 5시 줌 리플렉션 
 - [x] 6시에 회의 -: 
 - [ ] 환경변수 확인 
 - [ ] 소셜로그인 환경변수 재발급, 지도 API 키
 - [ ] 브랜치 머지: 8시 
 - [ ] 사이트에 더미사진 올리기
 - [ ] 위키페이지 워크로그 정리
 - [ ] API 문서 재검토(토요일 오전까지만)
 - [ ] 시스템 아키텍처 다시그리기
 - [ ] 환경변수 client ID, secret 재발급
---
주말
-(토)
 - [ ] 개인기술발표 준비!!
-(일)-(월)
 - [ ] 팀 발표자료 준비
 - [ ] 노션문서 준비 (-)
 - [ ] 발표 체크리스트 완성
