### ISSUE TITLE
[S] 추가작업 <보류>

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#268]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [ ] validator 모듈 적용
 - [ ] 사용자가 좋아요 한 글 시간순으로 정렬 
 - [ ] RDS 타임존 설정
 - [ ] id 값 계속 증가하는 문제 (https://wanna-b.tistory.com/47)
