### ISSUE TITLE
5.14 (토) 특이사항 여기에 남겨주세요!

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#274]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] 환경변수체크
 - [ ] **이메일 인증 다시 머지필요:** DB 테이블 컬럼 속성, 이메일 인증 로직 일부 로컬에서 수정 후 테스트해봤는데 이상은 없었음:
 - > 로직에서 이상했던 부분:  회원가입을 완료하지 않았는데도 platformType을 0번으로 두었던 점(**비회원은 platformtype null로 수정**)
 - > 비회원은 닉네임을 임의로 넣었었는데, 비밀번호만 null로 두는 것이 일관성에 어긋남. 비회원의 경우 **비밀번호와 닉네임 모두 nulll값**으로 두어야 합당. 추후 회원가입 시 다 채워질 항목들이고, 비회원의 경우 회원가입 미완료시 DB에서 삭제해버리기 때문에 괜찮다고 생각함 -> 임의의 닉네임 생성에 쓰였던 **nanoid 모듈 삭제**함.
 - > 이에 따른 DB 컬럼 속성 설정 완료
 - > 인증 완료 시, emailverified : 0 -> 1로 변경
 - > 가입 완료 시, platformType : 0, emailAuthCode: null로 업데이트 (이때서야 인증코드 삭제하는 이유는 같은 인증번호로 재인증하는 경우를 대비하기 위함.) 
 - [ ] **이메일 빈칸으로 두고 인증코드 버튼 누를 시, 이미 가입된 이메일이라 뜸** - 추후수정필요
 - [ ] 위키페이지 워크로그

## 오늘 다 같이 논의할 부분
https://www.notion.so/Final-Project-6e40d36b51d9426cb25bb49af80b0477
 - [x] 코드 특이사항이나 버그
 - [ ] 노션 문서 공통 페이지: 팀, 서비스, 스택소개 부분
 - [ ] 팀 발표자 선정
 - [x] 아래 항목들이 어떤 방식으로 들어가면 좋을 지 합의 필요함
 1. 서비스 소개
   - 어떠한 서비스인지 1분 이내로 설명
 
2. 프로젝트에 사용된 스택 
   - 서비스 구현을 위해 사용된 스택을 소개해 주시기 바랍니다. 
   - 단순히 사용되었다 뿐만 아니라, 어떠한 구조로 사용되었는지 아키텍처를 그림으로 표현합니다. 

3. 팀원 소개
   - 프로젝트에 참여한 팀원을 소개해 주시기 바랍니다. 
   - 해당 팀원의 사진, 이름, 기수, 포지션 등을 간단하게 소개해 주시기 바랍니다. 

4. 서비스 기능 시연
   - 구현된 서비스를 소개해 주시기 바랍니다. 
   - 단순한 기능들보다는 메인이 될 수 있는 기능을 소개해 주시기 바랍니다. 
   - 유저에게 서비스 소개를 한다고 생각해 주시기 바랍니다.

6.FAQ
   - 우리 서비스를 보고 가질 수 있는 질문에 대해 미리 질의응답을 진행합니다.
      ( 4 ~ 5개 정도로 모든 팀원이 답할 수 있으면 좋습니다. )
## 각자 마무리할 부분
 - [ ] 개인 기술발표 준비 마무리
 - [ ] 팀 발표자: PPT, 대본 준비 - 10분동안 서비스소개, 스택소개, 기능 시연**, 팀소개
 - [ ] 위키페이지 워크로그
 - [ ] 발표 질의응답 1분씩 준비
 - [ ] 팀 노션문서 개인 소개

## (월)
- [ ] 개인 기술발표 업로드
- [ ] 대본, PPT 마무리, 한번 더 확인
- [ ] 팀발표 녹화
- [ ] 노션문서 마무리
