### ISSUE TITLE
5/16 (월) 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#280]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] 팀 발표자료 중 모바일 움짤 준비
 - [ ] 발표자선정 및 녹화
 - [ ] 질의응답 각자녹화해서 올리고 편집
 - [ ] 팀 노션문서 공통부분 꾸미기
