### ISSUE TITLE
[C] 유저 / 회원가입

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#3]
# ISSUE
* Group: client
* Type: feature
* Detail: 유저 회원가입
 
# TODO
 - [x] email과 password(8~16자)와 retype(password와 같은지)을 입력받아 유효성 검사
 - [x] 통과하지 못하면, 빨간 글씨의 errorMessage
 - [x] 통과하면, 서버에 회원가입 요청
 - [x] 서버에서 성공 응답 오면 성공 모달
 - [x] 서버에서 email 중복 응답 오면 빨간 글씨의 errorMessage
 - [x] 서버코드랑 연결 확인
