### ISSUE TITLE
[S] 마이페이지-게시글 / 사진 삭제

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#30]
# ISSUE
* Group: `server`
* Type: `feature`
* Detail: 마이페이지에서의 사진 삭제 수도 코드 작성 및 기능 구현 

# TODO
 - [x] 클라이언트로부터 삭제하려는 사진 정보 받기
 - [x] 삭제 쿼리문 작성
 - [x] 삭제 컨트롤러 작성
