### ISSUE TITLE
[S] 백엔드 초기 세팅: 배포 및 모듈 설치

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#35]
# ISSUE
* Group: `server`, `sr`

# TODO
 ## 배포환경 설정
 - [x] 로컬에서 모듈 설치, 기본 서버 코드 작성(hello world만 보내주는 서버)
 - [x] 배포 담당을 어느 분의 레포로 진행할 것인가 정하기: 두명 다 배포 진행-> 실패할 경우 대비
 - [x] EC2  생성
 - [x] RDS 생성, 연결
 - [x] 로컬에서 RDS 연결 코드 작성, 
 - [x] 준비된 EC2로 자동 배포 파이프라인 만들기, 배포 환경에서 서버 구동 test(자동배포는 실패: 수동배포로 전환)
 - [x] 클라이언트 주소: localhost:3000
 - [x] 배포 완료 시 EC2 주소 알려드리기

## 설치 모듈 
dotenv
morgan, nodemon, expressjs, cors,
jsonwebtoken, bcrypt
axios (Oauth 로그인 기능 구현 가능할 때 사용)
express-validator(시간이 남으면 활용, -> 우선 최소 로그인 기능 구현해두고 이 미들웨어 넣어서 리팩토링 진행)
cookie-parser,
helmet
sequelize
sequelize-cli
mysql2 -> 프롬이스 지원으로 좀 더 편리하며 nodeJS와 mysql DB를 연결함

## 보류된 설치 모듈
multer, multer-s3(이미지 업로드 로직 정해지면 활용 예정)
