### ISSUE TITLE
4.21 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#38]
# ISSUE
* Group: `회의록`

# TODO
 - [x] 깃허브 위키페이지 중 Team Introduction 역할 채우기
 - [x] 3시전까지 SR 설문제출
 - [x] KPT 회고 작성
 - [x] 그 외 특이사항 있으면 공유
 - [x] 5시 모여서 진행상황 공유
