### ISSUE TITLE
[S] 배포 환경 세팅

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#4]
# ISSUE
Group: server 
Type: settings
Detail: 서버 배포 환경 세팅
# TODO
 - [x] EC2 인스턴스 생성
 - [ ] EC2 배포 자동화 환경 구축
-  [ ] 파이프라인 만들기
-  [x] RDS 연결
-  [x] 환경 변수 설정
