### ISSUE TITLE
[S] 백엔드 초기 세팅: 테이블, 디렉토리 구조 작성

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#49]
# ISSUE
* Group:`server`
* Type:  `feature`,
* Detail: 

# TODO
 - [x] 디렉토리 구조 작성
 - [x] RDS - mysql workbench 연결(https://durian9s-coding-tree.tistory.com/15, 포트번호는 RDS 포트번호 사용): 수현완료
 - [x] 라우터 구조 작성
 - [x] 식물 정보 사진 s3 서버 구축: 수현완료
 ## 테이블 작성 
 - [x] 마이그레이션 이슈: 테이블을 나눠서 작성하자.
 - [x] users 테이블 보완
 - [x] plants 테이블 : 
 - [x] *회의후 결정: plants_categories 테이블
 - [x] 유저와 plants 연결하는 interiors 
 - [x] 유저와 interiors 연결하는 interior_likes 
 - [x] comments 테이블 작성
