### ISSUE TITLE
[C] 모달 프레임 컴포넌트

### ISSUE THREAD

**Issue by yuriiiiiiiiiii** [codestates/Pida#53]
# ISSUE
* Group: `client`
* Type: feature`
* Detail: 여러 창에서 활용할 수 있도록 모달 프레임 컴포넌트를 만든다

# TODO
 - [x] component 폴더에 Modal 파일을 만들고 컨테이너, 백드롭, 뷰, 컨텐츠로 이루어진 Modal 컴포넌트 작성
 - [x] 로그인 완료 시 모달이 뜨도록 함
 - [x] 회원가입 완료 시 모달이 뜨도록 함
 - [x] 로그아웃 완료 시 모달이 뜨도록 함
