### ISSUE TITLE
4.23 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#55]
# ISSUE
* Group: `sr`
* Type: 
* Detail: 

# TODO

- [x] 서버 응답은 카멜 케이스로 변환해서 보내주도록 한다
 - [x]  DB 스키마 수정
 - [x] API 보완: DB 스키마 보고, 구현 ( -14:30 ) +댓글 작성하기 CRUD
 - [x] API  검토 (내가 업로드, 좋아요 한 인테리어 게시물들
=> 수정 및 삭제를 마이페이지에서만 할 것인가, 식물 상세페이지에서도 할 것인가?
=> 일단은 마이페이지에만 api작성해둘게요..!
=> 어찌보면, 그냥 엔드포인트는 하나로 두고 두 페이지에서 같은 엔드포인트 쓰도록 하는 것도 방법일거같다.)
 - [x] wikipage team rules 수정(주말규칙 얘기하는 김에 이번주 일요일 어떻게 진행 할건가 논의)
 - [x] wikipage requirements 수정
 - [ ] 사진 관련해서 조사 어떻게 할 것인가 논의/사진 구현은 병렬적으로 조사하며 진행
 - [ ] SR 마무리 후, 월요일 중~화요일  오전 DM. (스몰톡 준비..)

ref
https://www.moyamo.co.kr/

https://www.figma.com/file/owmajg3Cz93krTJv12ptKI/%EB%8D%94%ED%95%98%EB%8B%A4-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8---%EC%A7%80%EC%8B%9D%EC%8A%A4%ED%8F%B0%EC%84%9C---%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85-%EC%B5%9C%EC%A2%85?node-id=0%3A1

### 수정된 기획사안
+사진이랑 글이랑 같이 업로드 할 수 있으면 좋겠다
+회원정보 추가 : 닉네임 
+ 디폴트로 할 수 있는 기능들

+컨셉?:인테리어 질문 추가하고, 질문에 어울리는 사진 추가하고, => 페이지 넘김.
질문 자체를 없애고 컨셉에 맞는 사진들
사진은 천장에 매달린 식물
구석에 있는 식물
창문에 있는 식물

식물을 둘 위치 => 식물의 크기 => 꽃 유무

검색 결과로 넘어갔을 때는...
상세페이지에서는 일조량이나 키우기 난이도 풍량...식물 상세 설명

썸네일 사진의 경우는 기본으로 인테리어 한 사진 두기.

하단 인테리어 사진에서는 댓글 달 수 있음. 
사진 추가할 수 있다. 
사진 업로드 시, 글도 같이 쓸 수 있다. 
댓글 테이블은 심화로 빼기
