### ISSUE TITLE
4.25 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#57]
# ISSUE
* Group: `sr`
* Type: 
* Detail: 

# TODO

 - [x] API  특이사항 있었는지 확인
 - [x] 식물 자료조사 관련, 특이사항 논의 후 DB 테이블 확정
   - (사진 부족시: 더미 이용, 인테리어 사진 pinterest 등, 텍스트파일은 사진과 관련 없어도 일단 내용 채우기??, API)
   - 닉네임 최대 글자수 8자. 
   - 식물 DB 테이블은 별도의 카테고리 테이블 만들었음
 - [x] 식물 썸네일 사진: s3 이미지 버킷 구축 완료. DB에 url 저장 예정
 - [x] SR 내용: 반응형 와이어프레임..(이번 주  또는 구현하면서 보완?) ---> 보류!
 - [x] SR 보완 완료
 - [x] 이번 주차(2주차) 목표: DB 테이블 설계, 라우터 구조 작성, 검색 기능 구현, 유저 CRUD 구현
   - 1주차 태스크카드 일부 2주차로 이동 필요함.
   - 당일 작업 공유
   - 백엔드: API, 테이블 구조 확정, 테이블 구조작성, 라우터 구조 작성
   - 프론트엔드: 메인페이지, 로그인 회원가입 모달..
 - [x] 별도로 공부할 내용: 사진 업로드하는 로직(3주차부터 게시물 CRUD 위함, 평일 남는 시간 또는 주말 활용)
