### ISSUE TITLE
[S] 홈 / 검색 기능

### ISSUE THREAD

**Issue by neroaki** [codestates/Pida#6]
# ISSUE
* Group: `server`
* Type: `feature`
* Detail: 홈 (루트) 접속 시 유사 검색 기능 구현을 위한 페이지 제공
> - 선택지 버튼 클릭 시 sql 문 생성
> - 'where '
# TODO
 - [x] DB 더미데이터 채우기
 - [x] 검색 컨트롤러 작성
 - [x] sql 문 작성 및 테스트(포스트맨 등 활용)
