### ISSUE TITLE
4.27 회의록 

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#72]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
#### 백엔드 & 프론트엔드
 - [x] plant 검색기능 구현, DB 테이블 완성

 - [x] 로그인 - https 배포 관련: 오늘 작업 마무리 하고, EC2 하나로만 배포 들어갈 예정.
 - [x] 배포 흐름: 프론트에서 도메인 구매 후 서버 측에서 해당도메인 연결해 줄 것

#### 배포 전 마무리할 작업(~)
 - [x] 회원 관련은 일단 코드 작성 후 로컬에서 테스트, 머지.(로그인 쿠키 발급이 안되므로 우선은 이렇게.) or 배포 먼저 후 코드 작성..?
 - [x]  회원정보 조회 리팩터, 및 회원정보 수정 구현: 더미 데이터 넣고 우선 로컬에서 테스트
 - [x]  혹시 모르니, 토큰을 응답 바디에 담아 보내는 코드도 주석으로 풀어서 작성하기. 
#### 배포 이후 이어 할 작업
 - [x] 로그인 시 쿠키 저장 문제 확인
