### ISSUE TITLE
[S] 닉네임 수정 및 회원정보 조회 컨트롤러 테스트, https 배포

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#75]
# ISSUE
* Group: `server`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [x] 현재까지 토큰을 응답 바디로 돌려주었을 때 정상 작동하는 것으로 확인된 컨트롤러: 로그인, 로그아웃, 비번변경, 탈퇴
 - [x] 회원정보조회 & 닉네임 변경 로컬에서 테스트 하고 머지
 - [x] 쿠키 설정 머지:  수현
#### https 배포 테스트: 
 - [x]  서버 https 배포주소 알려드리기
 - [x]  회원가입
 - [x]  로그인
 - [x]  로그아웃
 - [x]  닉넴수정
 - [x] 비번수정
 - [x] 회원탈퇴
 - [x] 회원정보조회
 - [x] 검색결과이미지(http 이슈. 있을 시 해당 s3도 https배포 필요.)
 - [x] DB 스키마 수정
