### ISSUE TITLE
스몰톡 안건 정리

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#79]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO
 - [ ] 현재상황: https 배포 & 회원정보조회/수정까지 : 메인 기능 구현하기까지 조금 속도 내야 할 수도 있음.
 - [ ] 와이어프레임
 - [ ] 멘탈..
 - [ ] 이대로 진행 계속해도 괜찮은가...
 - [ ] 이미지 저작권!!! 지금은 사진자료가 부족해서 저작권 있는 이미지 가져다 쓴 게 대부분인데 추후 저작권 없는 이미지로 바꿔야 할까요..고민이 됩니다!!!!
 - [ ] 식물 있는 인테리어 사진: 식물 없어도 보여주어도 될까요,,,,,!
 - [ ] 기능에 초점을 둘지. 사진도 중요하게 생각해야 하는지....
