### ISSUE TITLE
[C] 유저 / 로그아웃

### ISSUE THREAD

**Issue by osuhao** [codestates/Pida#8]
# ISSUE
* Group: `client`
* Type:`feature`
* Detail: 로그아웃 기능 구현

# TODO
 - [x] 서버에 로그아웃 요청
 - [x] 서버에서 성공 응답오면 성공 모달
 - [x] 서버코드랑 연결 확인
