### ISSUE TITLE
[C] 인테리어 글 / 수정

### ISSUE THREAD

**Issue by yuriiiiiiiiiii** [codestates/Pida#87]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail: 

# TODO
 - [x] 기존의 이미지와 내용을 가져와 초기값으로 설정
 - [x] 사용자가 새 이미지나 내용을 입력하면 그 값을 받아옴
 - [x] 버튼을 누르면 서버에 수정 요청
