### ISSUE TITLE
[C] 댓글 / 수정

### ISSUE THREAD

**Issue by yuriiiiiiiiiii** [codestates/Pida#89]
# ISSUE
* Group: `client`
* Type: `feature`
* Detail: 유저는 자신이 쓴 댓글을 수정할 수 있습니다.

# TODO
 - [x] PATCH 요청 서버에 보내기
 - [x] 글을 쓴 유저가 맞는지 확인
 - [x] 서버와의 연결 확인
