### ISSUE TITLE
[S] 회원 정보 관련 버그 수정 & 검색 쿼리 점검 

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#95]
# ISSUE
* Group:`server`
* Type: `bug`, `feature`
* Detail: 

# TODO
 - [x] 회원 관련 로직 전체 테스트!
 - [x] 회원정보 조회 응답 형식 api에 맞게 수정!
 - [x] 검색 부분 쿼리 점검 
 - [x] 검색 후 식물 상세정보 페이지 컨트롤러 작성
 - [x] csv 로 다른 rds 더미데이터 채우기
