### ISSUE TITLE
4.29 회의록

### ISSUE THREAD

**Issue by suxxzzy** [codestates/Pida#98]
# ISSUE
* Group: `client`, `server`, `sr`
* Type: `bug`, `feature`, `delete`
* Detail: 

# TODO

글: 
클라: 채팅기능 와이어프레임까지만 * 닉네임 눌렀을 때!/ 
채팅의 비공개성 이용해서 유저간 소통 좀 더 강화
페이지네이션은 어드반스드.= 글부터 처리 후 생각

다음주 : 게시글(사진업로드) 댓글 좋아요 CRUD + 채팅기능 

마지막주: 세부적인 부분(소셜로그인/이메일 인증, 페이지네이션 등)  

* 데브로그! : 10시 전후.
* 오후 5시

- [x] 회원가입: 이메일 중복 체크 확인 <- 라우터 보완 선결
- [ ] 사진: 아래 노션 페이지와 댓글을 참고해 사진 자료 보완 (주말 간)
> - [링크](https://sponge-handbell-9a2.notion.site/API-94049e0c59eb48bf809fc708027193ce)
- [x] 프론트엔드: 댓글 CRD 작성 중
- [x] 백엔드: 댓글 CRUD 
- [ ] 백엔드: 게시글 CRUD 
- [ ] 전체: 이미지 업로드 로직 작성을 위한 사전 자료 수집
